function [SampleInfo,SampleFields] = ConvertTCGA_IdAEB(IDs)
% Converts TCGA sample ID into info
% TCGA-A6-2678-01A-01D-0820-05
% See https://wiki.nci.nih.gov/display/TCGA/TCGA+barcode for more info


SampleTypeIndx ={'01','Primary solid Tumor','TP';...
    '02','Recurrent Solid Tumor','TR';...
    '03','Primary Blood Derived Cancer - Peripheral Blood','TB';...
    '04','Recurrent Blood Derived Cancer - Bone Marrow','TRBM';...
    '05','Additional - New Primary','TAP';...
    '06','Metastatic','TM';...
    '07','Additional Metastatic','TAM';...
    '08','Human Tumor Original Cells','THOC';...
    '09','Primary Blood Derived Cancer - Bone Marrow','TBM';...
    '10','Blood Derived Normal','NB';...
    '11','Solid Tissue Normal','NT';...
    '12','Buccal Cell Normal','NBC';...
    '13','EBV Immortalized Normal','NEBV';...
    '14','Bone Marrow Normal','NBM';...
    '20','Control Analyte','CELLC';...
    '40','Recurrent Blood Derived Cancer - Peripheral Blood','TRB';...
    '50','Cell Lines','CELL';...
    '60','Primary Xenograft Tissue','XP';...
    '61','Cell Line Derived Xenograft Tissue','XCL'};


TSS_Indx = {'01','International Genomics Consortium','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '02','MD Anderson Cancer Center','Glioblastoma multiforme','IGC','GBM';...
    '04','Gynecologic Oncology Group','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '05','Indivumed','Lung adenocarcinoma','IGC','LUAD';...
    '06','Henry Ford Hospital','Glioblastoma multiforme','IGC','GBM';...
    '07','TGen','Cell Line Control','IGC','CellLine';...
    '08','UCSF','Glioblastoma multiforme','IGC','GBM';...
    '09','UCSF','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '10','MD Anderson Cancer Center','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '11','MD Anderson Cancer Center','Lung squamous cell carcinoma','IGC','LUSC';...
    '12','Duke','Glioblastoma multiforme','IGC','GBM';...
    '13','Memorial Sloan Kettering','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '14','Emory University','Glioblastoma multiforme','IGC','GBM';...
    '15','Mayo Clinic - Rochester','Glioblastoma multiforme','IGC','GBM';...
    '16','Toronto Western Hospital','Glioblastoma multiforme','IGC','GBM';...
    '17','Washington University','Lung adenocarcinoma','IGC','LUAD';...
    '18','Princess Margaret Hospital (Canada)','Lung squamous cell carcinoma','IGC','LUSC';...
    '19','Case Western','Glioblastoma multiforme','IGC','GBM';...
    '1Z','Johns Hopkins','Thymoma','NCH','THYM';...
    '20','Fox Chase Cancer Center','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '21','Fox Chase Cancer Center','Lung squamous cell carcinoma','IGC','LUSC';...
    '22','Mayo Clinic - Rochester','Lung squamous cell carcinoma','IGC','LUSC';...
    '23','Cedars Sinai','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '24','Washington University','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '25','Mayo Clinic - Rochester','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '26','University of Florida','Glioblastoma multiforme','IGC','GBM';...
    '27','Milan - Italy, Fondazione IRCCS Instituto Neuroligico C. Besta','Glioblastoma multiforme','IGC','GBM';...
    '28','Cedars Sinai','Glioblastoma multiforme','IGC','GBM';...
    '29','Duke','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '2A','Memorial Sloan Kettering Cancer Center','Prostate adenocarcinoma','NCH','PRAD';...
    '2E','University of Kansas Medical Center','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    '2F','Erasmus MC','Bladder Urothelial Carcinoma','NCH','BLCA';...
    '2G','Erasmus MC','Testicular Germ Cell Tumors','NCH','TGCT';...
    '2H','Erasmus MC','Esophageal carcinoma ','NCH','ESCA';...
    '2J','Mayo Clinic','Pancreatic adenocarcinoma','NCH','PAAD';...
    '2K','Greenville Health System','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    '2L','Technical University of Munich','Pancreatic adenocarcinoma','NCH','PAAD';...
    '2M','Technical University of Munich','Esophageal carcinoma ','NCH','ESCA';...
    '2N','Technical University of Munich','Stomach adenocarcinoma','NCH','STAD';...
    '2P','University of California San Diego','Pancreatic adenocarcinoma','NCH','PAAD';...
    '2V','University of California San Diego','Liver hepatocellular carcinoma','NCH','LIHC';...
    '2W','University of New Mexico','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    '2X','ABS IUPUI','Testicular Germ Cell Tumors','NCH','TGCT';...
    '2Y','Moffitt Cancer Center','Liver hepatocellular carcinoma','NCH','LIHC';...
    '2Z','Moffitt Cancer Center','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    '30','Harvard','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '31','Imperial College','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '32','St. Josephs Hospital (AZ)','Glioblastoma multiforme','IGC','GBM';...
    '33','Johns Hopkins','Lung squamous cell carcinoma','IGC','LUSC';...
    '34','University of Pittsburgh','Lung squamous cell carcinoma','IGC','LUSC';...
    '35','Cureline','Lung adenocarcinoma','IGC','LUAD';...
    '36','BC Cancer Agency','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '37','Cureline','Lung squamous cell carcinoma','IGC','LUSC';...
    '38','UNC','Lung adenocarcinoma','IGC','LUAD';...
    '39','MSKCC','Lung squamous cell carcinoma','IGC','LUSC';...
    '3A','Moffitt Cancer Center','Pancreatic adenocarcinoma','NCH','PAAD';...
    '3B','Moffitt Cancer Center','Sarcoma','NCH','SARC';...
    '3C','Columbia University','Breast invasive carcinoma','NCH','BRCA';...
    '3E','Columbia University','Pancreatic adenocarcinoma','NCH','PAAD';...
    '3G','MD Anderson Cancer Center','Thymoma','NCH','THYM';...
    '3H','MD Anderson Cancer Center','Mesothelioma','NCH','MESO';...
    '3J','Carle Cancer Center','Breast invasive carcinoma','NCH','BRCA';...
    '3K','Boston Medical Center','Liver hepatocellular carcinoma','NCH','LIHC';...
    '3L','Albert Einstein Medical Center','Colon adenocarcinoma','NCH','COAD';...
    '3M','University of Kansas Medical Center','Stomach adenocarcinoma','NCH','STAD';...
    '3N','Greenville Health System','Skin Cutaneous Melanoma','NCH','SKCM';...
    '3P','Greenville Health System','Ovarian serous cystadenocarcinoma','NCH','OV';...
    '3Q','Greenville Health Systems','Thymoma','NCH','THYM';...
    '3R','University of New Mexico','Sarcoma','NCH','SARC';...
    '3S','University of New Mexico','Thymoma','NCH','THYM';...
    '3T','Emory University','Thymoma','NCH','THYM';...
    '3U','University of Chicago','Mesothelioma','NCH','MESO';...
    '3W','University of California San Diego','Sarcoma','NCH','SARC';...
    '3X','Alberta Health Services','Cholangiocarcinoma','NCH','CHOL';...
    '3Z','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Kidney renal clear cell carcinoma','NCH','KIRC';...
    '41','Christiana Healthcare','Glioblastoma multiforme','IGC','GBM';...
    '42','Christiana Healthcare','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '43','Christiana Healthcare','Lung squamous cell carcinoma','IGC','LUSC';...
    '44','Christiana Healthcare','Lung adenocarcinoma','IGC','LUAD';...
    '46','St. Josephs Medical Center (MD)','Lung squamous cell carcinoma','IGC','LUSC';...
    '49','Johns Hopkins','Lung adenocarcinoma','IGC','LUAD';...
    '4A','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    '4B','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Lung adenocarcinoma','NCH','LUAD';...
    '4C','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Thyroid carcinoma','NCH','THCA';...
    '4D','Molecular Response','Ovarian serous cystadenocarcinoma','NCH','OV';...
    '4E','Molecular Response','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    '4G','Sapienza University of Rome','Cholangiocarcinoma','NCH','CHOL';...
    '4H','Proteogenex, Inc.','Breast invasive carcinoma','NCH','BRCA';...
    '4J','Proteogenex, Inc.','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    '4K','Proteogenex, Inc.','Testicular Germ Cell Tumors','NCH','TGCT';...
    '4L','Proteogenex, Inc.','Prostate adenocarcinoma','NCH','PRAD';...
    '4N','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Colon adenocarcinoma','NCH','COAD';...
    '4P','Duke University','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    '4Q','Duke University','Sarcoma','NCH','SARC';...
    '4R','Duke University','Liver hepatocellular carcinoma','NCH','LIHC';...
    '4S','Duke University','Prostate adenocarcinoma','NCH','PRAD';...
    '4T','Duke University','Colon adenocarcinoma','NCH','COAD';...
    '4V','Hospital Louis Pradel','Thymoma','NCH','THYM';...
    '4W','University of Miami','Glioblastoma multiforme','NCH','GBM';...
    '4X','Yale University','Thymoma','NCH','THYM';...
    '4Y','Medical College of Wisconsin','Sarcoma','NCH','SARC';...
    '4Z','Barretos Cancer Hospital','Bladder Urothelial Carcinoma','NCH','BLCA';...
    '50','University of Pittsburgh','Lung adenocarcinoma','IGC','LUAD';...
    '51','UNC','Lung squamous cell carcinoma','IGC','LUSC';...
    '52','University of Miami','Lung squamous cell carcinoma','IGC','LUSC';...
    '53','University of Miami','Lung adenocarcinoma','IGC','LUAD';...
    '55','International Genomics Consortium','Lung adenocarcinoma','IGC','LUAD';...
    '56','International Genomics Consortium','Lung squamous cell carcinoma','IGC','LUSC';...
    '57','International Genomics Consortium','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '58','Thoraxklinik at University Hospital Heidelberg','Lung squamous cell carcinoma','IGC','LUSC';...
    '59','Roswell Park','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '5A','Wake Forest University','Cholangiocarcinoma','NCH','CHOL';...
    '5B','Medical College of Wisconsin','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    '5C','Cureline','Liver hepatocellular carcinoma','NCH','LIHC';...
    '5D','University of Miami','Sarcoma','NCH','SARC';...
    '5F','Duke University','Thyroid carcinoma','NCH','THCA';...
    '5G','Cleveland Clinic Foundation','Thymoma','NCH','THYM';...
    '5H','Retina Consultants Houston','Uveal Melanoma','NCH','UVM';...
    '5J','Cureline','Acute Myeloid Leukemia','NCH','LAML';...
    '5K','St. Josephs Hospital AZ','Thymoma','NCH','THYM';...
    '5L','University of Sao Paulo','Breast invasive carcinoma','NCH','BRCA';...
    '5M','University of Sao Paulo','Colon adenocarcinoma','NCH','COAD';...
    '5N','University Hospital Erlangen','Bladder Urothelial Carcinoma','NCH','BLCA';...
    '5P','University Hospital Erlangen','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    '5Q','Proteogenex, Inc','Pancreatic adenocarcinoma','NCH','PAAD';...
    '5R','Proteogenex, Inc','Liver hepatocellular carcinoma','NCH','LIHC';...
    '5S','Holy Cross','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    '5T','Holy Cross','Breast invasive carcinoma','NCH','BRCA';...
    '5U','Regina Elena National Cancer Institute','Thymoma','NCH','THYM';...
    '5V','Roswell Park','Thymoma','NCH','THYM';...
    '5W','University of Alabama','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    '5X','University of Alabama','Ovarian serous cystadenocarcinoma','NCH','OV';...
    '60','Roswell Park','Lung squamous cell carcinoma','IGC','LUSC';...
    '61','University of Pittsburgh','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '62','Thoraxklinik at University Hospital Heidelberg','Lung adenocarcinoma','IGC','LUAD';...
    '63','Ontario Institute for Cancer Research','Lung squamous cell carcinoma','IGC','LUSC';...
    '64','Fox Chase','Lung adenocarcinoma','IGC','LUAD';...
    '65','Roswell Park','Glioblastoma multiforme','IGC','GBM';...
    '66','Indivumed','Lung squamous cell carcinoma','IGC','LUSC';...
    '67','St Josephs Medical Center (MD)','Lung adenocarcinoma','IGC','LUAD';...
    '68','Washington University - Cleveland Clinic','Lung squamous cell carcinoma','IGC','LUSC';...
    '69','Washington University - Cleveland Clinic','Lung adenocarcinoma','IGC','LUAD';...
    '6A','University of Kansas','Lung squamous cell carcinoma','NCH','LUSC';...
    '6D','University of Oklahoma HSC','Kidney renal clear cell carcinoma','NCH','KIRC';...
    '6G','University of Sao Paulo','Rectum adenocarcinoma','NCH','READ';...
    '6H','Test For lcml','Chronic Myelogenous Leukemia','NCH','LCML';...
    '70','ILSBio','Lung squamous cell carcinoma','IGC','LUSC';...
    '71','ILSBio','Lung adenocarcinoma','IGC','LUAD';...
    '72','NCH','Ovarian serous cystadenocarcinoma','IGC','OV';...
    '73','Roswell Park','Lung adenocarcinoma','IGC','LUAD';...
    '74','Swedish Neurosciences','Glioblastoma multiforme','IGC','GBM';...
    '75','Ontario Institute for Cancer Research (OICR)','Lung adenocarcinoma','IGC','LUAD';...
    '76','Thomas Jefferson University','Glioblastoma multiforme','IGC','GBM';...
    '77','Prince Charles Hospital','Lung squamous cell carcinoma','IGC','LUSC';...
    '78','Prince Charles Hospital','Lung adenocarcinoma','IGC','LUAD';...
    '79','Ontario Institute for Cancer Research (OICR)/Ottawa','Lung squamous cell carcinoma','IGC','LUSC';...
    '80','Ontario Institute for Cancer Research (OICR)/Ottawa','Lung adenocarcinoma','IGC','LUAD';...
    '81','CHI-Penrose Colorado','Glioblastoma multiforme','IGC','GBM';...
    '82','CHI-Penrose Colorado','Lung squamous cell carcinoma','IGC','LUSC';...
    '83','CHI-Penrose Colorado','Lung adenocarcinoma','IGC','LUAD';...
    '85','Asterand','Lung squamous cell carcinoma','IGC','LUSC';...
    '86','Asterand','Lung adenocarcinoma','IGC','LUAD';...
    '87','International Genomics Consortium','Glioblastoma multiforme','IGC','GBM';...
    '90','ABS - IUPUI','Lung squamous cell carcinoma','IGC','LUSC';...
    '91','ABS - IUPUI','Lung adenocarcinoma','IGC','LUAD';...
    '92','Washington University - St. Louis','Lung squamous cell carcinoma','IGC','LUSC';...
    '93','Washington University - St. Louis','Lung adenocarcinoma','IGC','LUAD';...
    '94','Washington University - Emory','Lung squamous cell carcinoma','IGC','LUSC';...
    '95','Washington University - Emory','Lung adenocarcinoma','IGC','LUAD';...
    '96','Washington University - NYU','Lung squamous cell carcinoma','IGC','LUSC';...
    '97','Washington University - NYU','Lung adenocarcinoma','IGC','LUAD';...
    '98','Washington University - Alabama','Lung squamous cell carcinoma','IGC','LUSC';...
    '99','Washington University - Alabama','Lung adenocarcinoma','IGC','LUAD';...
    'A1','UCSF','Breast invasive carcinoma','NCH','BRCA';...
    'A2','Walter Reed','Breast invasive carcinoma','NCH','BRCA';...
    'A3','International Genomics Consortium','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'A4','International Genomics Consortium','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'A5','Cedars Sinai','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'A6','Christiana Healthcare','Colon adenocarcinoma','IGC','COAD';...
    'A7','Christiana Healthcare','Breast invasive carcinoma','NCH','BRCA';...
    'A8','Indivumed','Breast invasive carcinoma','NCH','BRCA';...
    'AA','Indivumed','Colon adenocarcinoma','IGC','COAD';...
    'AB','Washington University','Acute Myeloid Leukemia','NCH','LAML';...
    'AC','International Genomics Consortium','Breast invasive carcinoma','NCH','BRCA';...
    'AD','International Genomics Consortium','Colon adenocarcinoma','IGC','COAD';...
    'AF','Christiana Healthcare','Rectum adenocarcinoma','IGC','READ';...
    'AG','Indivumed','Rectum adenocarcinoma','IGC','READ';...
    'AH','International Genomics Consortium','Rectum adenocarcinoma','IGC','READ';...
    'AJ','International Genomics Conosrtium','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'AK','Fox Chase','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'AL','Fox Chase','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'AM','Cureline','Colon adenocarcinoma','IGC','COAD';...
    'AN','Cureline','Breast invasive carcinoma','NCH','BRCA';...
    'AO','MSKCC','Breast invasive carcinoma','NCH','BRCA';...
    'AP','MSKCC','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'AQ','UNC ','Breast invasive carcinoma','NCH','BRCA';...
    'AR','Mayo','Breast invasive carcinoma','NCH','BRCA';...
    'AS','St. Josephs Medical Center-(MD)','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'AT','St. Josephs Medical Center-(MD)','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'AU','St. Josephs Medical Center-(MD)','Colon adenocarcinoma','IGC','COAD';...
    'AV','NCH','Cell Line Control','NCH','CellLine';...
    'AW','Cureline','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'AX','Gynecologic Oncology Group','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'AY','UNC','Colon adenocarcinoma','IGC','COAD';...
    'AZ','University of Pittsburgh','Colon adenocarcinoma','IGC','COAD';...
    'B0','University of Pittsburgh','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'B1','University of Pittsburgh','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'B2','Christiana Healthcare','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'B3','Christiana Healthcare','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'B4','Cureline','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'B5','Duke','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'B6','Duke','Breast invasive carcinoma','NCH','BRCA';...
    'B7','Cureline','Stomach adenocarcinoma','IGC','STAD';...
    'B8','UNC','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'B9','UNC','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'BA','UNC','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'BB','Johns Hopkins','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'BC','UNC','Liver hepatocellular carcinoma','NCH','LIHC';...
    'BD','University of Pittsburgh','Liver hepatocellular carcinoma','NCH','LIHC';...
    'BF','Cureline','Skin Cutaneous Melanoma','NCH','SKCM';...
    'BG','University of Pittsburgh','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'BH','University of Pittsburgh','Breast invasive carcinoma','NCH','BRCA';...
    'BI','University of Pittsburgh','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'BJ','University of Pittsburgh','Thyroid carcinoma','IGC','THCA';...
    'BK','Christiana Healthcare','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'BL','Christiana Healthcare','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'BM','UNC','Rectum adenocarcinoma','IGC','READ';...
    'BP','MSKCC','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'BQ','MSKCC','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'BR','Asterand','Stomach adenocarcinoma','IGC','STAD';...
    'BS','University of Hawaii','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'BT','University of Pittsburgh','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'BW','St. Josephs Medical Center-(MD)','Liver hepatocellular carcinoma','NCH','LIHC';...
    'C4','Indivumed','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'C5','Medical College of Wisconsin','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'C8','ILSBio','Breast invasive carcinoma','NCH','BRCA';...
    'C9','ILSBio','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'CA','ILSBio','Colon adenocarcinoma','IGC','COAD';...
    'CB','ILSBio','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'CC','ILSBio','Liver hepatocellular carcinoma','NCH','LIHC';...
    'CD','ILSBio','Stomach adenocarcinoma','IGC','STAD';...
    'CE','ILSBio','Thyroid carcinoma','IGC','THCA';...
    'CF','ILSBio','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'CG','Indivumed','Stomach adenocarcinoma','IGC','STAD';...
    'CH','Indivumed','Prostate adenocarcinoma','IGC','PRAD';...
    'CI','University of Pittsburgh','Rectum adenocarcinoma','IGC','READ';...
    'CJ','MD Anderson Cancer Center','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'CK','Harvard','Colon adenocarcinoma','IGC','COAD';...
    'CL','Harvard','Rectum adenocarcinoma','IGC','READ';...
    'CM','MSKCC','Colon adenocarcinoma','IGC','COAD';...
    'CN','University of Pittsburgh','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'CQ','University Health Network, Toronto','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'CR','Vanderbilt University','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'CS','Thomas Jefferson University','Brain Lower Grade Glioma','IGC','LGG';...
    'CU','UNC','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'CV','MD Anderson Cancer Center','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'CW','Mayo Clinic - Rochester','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'CX','Medical College of Georgia','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'CZ','Harvard','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'D1','Mayo Clinic','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'D3','MD Anderson','Skin Cutaneous Melanoma','NCH','SKCM';...
    'D5','Greater Poland Cancer Center','Colon adenocarcinoma','IGC','COAD';...
    'D6','Greater Poland Cancer Center','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'D7','Greater Poland Cancer Center','Stomach adenocarcinoma','IGC','STAD';...
    'D8','Greater Poland Cancer Center','Breast invasive carcinoma','NCH','BRCA';...
    'D9','Greater Poland Cancer Center','Skin Cutaneous Melanoma','NCH','SKCM';...
    'DA','Yale','Skin Cutaneous Melanoma','NCH','SKCM';...
    'DB','Mayo Clinic - Rochester','Brain Lower Grade Glioma','IGC','LGG';...
    'DC','MSKCC','Rectum adenocarcinoma','IGC','READ';...
    'DD','Mayo Clinic - Rochester','Liver hepatocellular carcinoma','NCH','LIHC';...
    'DE','University of North Carolina','Thyroid carcinoma','NCH','THCA';...
    'DF','Ontario Institute for Cancer Research','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'DG','Ontario Institute for Cancer Research','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'DH','University of Florida','Brain Lower Grade Glioma','IGC','LGG';...
    'DI','MD Anderson','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'DJ','Memorial Sloan Kettering','Thyroid carcinoma','NCH','THCA';...
    'DK','Memorial Sloan Kettering','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'DM','University Of Michigan','Colon adenocarcinoma','NCH','COAD';...
    'DO','Medical College of Georgia','Thyroid carcinoma','NCH','THCA';...
    'DQ','University Of Michigan','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'DR','University of Hawaii','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'DS','Cedars Sinai','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'DT','ILSBio','Rectum adenocarcinoma','IGC','READ';...
    'DU','Henry Ford Hospital','Brain Lower Grade Glioma','IGC','LGG';...
    'DV','NCI Urologic Oncology Branch','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'DW','NCI Urologic Oncology Branch','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'DX','Memorial Sloan Kettering','Sarcoma','NCH','SARC';...
    'DY','University Of Michigan','Rectum adenocarcinoma','NCH','READ';...
    'DZ','Mayo Clinic - Rochester','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'E1','Duke','Brain Lower Grade Glioma','IGC','LGG';...
    'E2','Roswell Park','Breast invasive carcinoma','NCH','BRCA';...
    'E3','Roswell Park','Thyroid carcinoma','NCH','THCA';...
    'E5','Roswell Park','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'E6','Roswell Park','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'E7','Asterand','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'E8','Asterand','Thyroid carcinoma','NCH','THCA';...
    'E9','Asterand','Breast invasive carcinoma','NCH','BRCA';...
    'EA','Asterand','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'EB','Asterand','Skin Cutaneous Melanoma','NCH','SKCM';...
    'EC','Asterand','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'ED','Asterand','Liver hepatocellular carcinoma','NCH','LIHC';...
    'EE','University of Sydney','Skin Cutaneous Melanoma','NCH','SKCM';...
    'EF','Cureline','Rectum adenocarcinoma','IGC','READ';...
    'EI','Greater Poland Cancer Center','Rectum adenocarcinoma','IGC','READ';...
    'EJ','University of Pittsburgh','Prostate adenocarcinoma','IGC','PRAD';...
    'EK','Gynecologic Oncology Group','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'EL','MD Anderson','Thyroid carcinoma','NCH','THCA';...
    'EM','University Health Network','Thyroid carcinoma','NCH','THCA';...
    'EO','University Health Network','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'EP','Christiana Healthcare','Liver hepatocellular carcinoma','NCH','LIHC';...
    'EQ','Christiana Healthcare','Stomach adenocarcinoma','IGC','STAD';...
    'ER','University of Pittsburgh','Skin Cutaneous Melanoma','NCH','SKCM';...
    'ES','University of Florida','Liver hepatocellular carcinoma','NCH','LIHC';...
    'ET','Johns Hopkins','Thyroid carcinoma','NCH','THCA';...
    'EU','CHI-Penrose Colorado','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'EV','CHI-Penrose Colorado','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'EW','University of Miami','Breast invasive carcinoma','NCH','BRCA';...
    'EX','University of North Carolina','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'EY','University of North Carolina','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'EZ','UNC','Brain Lower Grade Glioma','IGC','LGG';...
    'F1','UNC','Stomach adenocarcinoma','IGC','STAD';...
    'F2','UNC','Pancreatic adenocarcinoma','IGC','PAAD';...
    'F4','Asterand','Colon adenocarcinoma','IGC','COAD';...
    'F5','Asterand','Rectum adenocarcinoma','IGC','READ';...
    'F6','Asterand','Brain Lower Grade Glioma','IGC','LGG';...
    'F7','Asterand','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'F9','Asterand','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'FA','Asterand','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'FB','Asterand','Pancreatic adenocarcinoma','IGC','PAAD';...
    'FC','Asterand','Prostate adenocarcinoma','IGC','PRAD';...
    'FD','BLN - University Of Chicago','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'FE','Ohio State University','Thyroid carcinoma','NCH','THCA';...
    'FF','SingHealth','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'FG','Case Western','Brain Lower Grade Glioma','IGC','LGG';...
    'FH','CHI-Penrose Colorado','Thyroid carcinoma','NCH','THCA';...
    'FI','Washington University','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'FJ','BLN - Baylor','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'FK','Johns Hopkins','Thyroid carcinoma','NCH','THCA';...
    'FL','University of Hawaii - Normal Study','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'FM','International Genomics Consortium','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'FN','International Genomics Consortium','Brain Lower Grade Glioma','IGC','LGG';...
    'FP','International Genomics Consortium','Stomach adenocarcinoma','IGC','STAD';...
    'FQ','Johns Hopkins','Pancreatic adenocarcinoma','IGC','PAAD';...
    'FR','University of North Carolina','Skin Cutaneous Melanoma','NCH','SKCM';...
    'FS','Essen','Skin Cutaneous Melanoma','NCH','SKCM';...
    'FT','BLN - University of Miami','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'FU','International Genomics Consortium','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'FV','International Genomics Consortium','Liver hepatocellular carcinoma','NCH','LIHC';...
    'FW','International Genomics Consortium','Skin Cutaneous Melanoma','NCH','SKCM';...
    'FX','International Genomics Consortium','Sarcoma','NCH','SARC';...
    'FY','International Genomics Consortium','Thyroid carcinoma','NCH','THCA';...
    'FZ','University of Pittsburgh','Pancreatic adenocarcinoma','IGC','PAAD';...
    'G2','MD Anderson','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'G3','Alberta Health Services','Liver hepatocellular carcinoma','NCH','LIHC';...
    'G4','Roswell Park','Colon adenocarcinoma','IGC','COAD';...
    'G5','Roswell Park','Rectum adenocarcinoma','IGC','READ';...
    'G6','Roswell Park','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'G7','Roswell Park','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'G8','Roswell Park','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'G9','Roswell Park','Prostate adenocarcinoma','IGC','PRAD';...
    'GC','International Genomics Consortium','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'GD','ABS - IUPUI','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'GE','ABS - IUPUI','Thyroid carcinoma','NCH','THCA';...
    'GF','ABS - IUPUI','Skin Cutaneous Melanoma','NCH','SKCM';...
    'GG','ABS - IUPUI','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'GH','ABS - IUPUI','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'GI','ABS - IUPUI','Breast invasive carcinoma','NCH','BRCA';...
    'GJ','ABS - IUPUI','Liver hepatocellular carcinoma','NCH','LIHC';...
    'GK','ABS - IUPUI','Kidney renal clear cell carcinoma','IGC','KIRC';...
    'GL','ABS - IUPUI','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'GM','MD Anderson','Breast invasive carcinoma','NCH','BRCA';...
    'GN','Roswell','Skin Cutaneous Melanoma','NCH','SKCM';...
    'GP','MD Anderson','Acute Myeloid Leukemia','NCH','LAML';...
    'GR','University of Nebraska Medical Center (UNMC)','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'GS','Fundacio Clinic per a la Recerca Biomedica','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'GU','BLN - UT Southwestern Medical Center at Dallas','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'GV','BLN - Cleveland Clinic','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'GZ','BC Cancer Agency','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'H1','Medical College of Georgia','Stomach adenocarcinoma','IGC','STAD';...
    'H2','Christiana Healthcare','Thyroid carcinoma','NCH','THCA';...
    'H3','ABS - IUPUI','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','IGC','DLBC';...
    'H4','Medical College of Georgia','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'H5','Medical College of Georgia','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'H6','Christiana Healthcare','Pancreatic adenocarcinoma','IGC','PAAD';...
    'H7','ABS - IUPUI','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'H8','ABS - IUPUI','Pancreatic adenocarcinoma','IGC','PAAD';...
    'H9','ABS - IUPUI','Prostate adenocarcinoma','IGC','PRAD';...
    'HA','Alberta Health Services','Stomach adenocarcinoma','IGC','STAD';...
    'HB','University of North Carolina','Sarcoma','NCH','SARC';...
    'HC','International Genomics Consortium','Prostate adenocarcinoma','IGC','PRAD';...
    'HD','International Genomics Consortium','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'HE','Ontario Institute for Cancer Research (OICR)','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'HF','Ontario Institute for Cancer Research (OICR)','Stomach adenocarcinoma','IGC','STAD';...
    'HG','Roswell Park','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'HH','Fox Chase','Stomach adenocarcinoma','IGC','STAD';...
    'HI','Fox Chase','Prostate adenocarcinoma','IGC','PRAD';...
    'HJ','Fox Chase','Stomach adenocarcinoma','IGC','STAD';...
    'HK','Fox Chase','Brain Lower Grade Glioma','IGC','LGG';...
    'HL','Fox Chase','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'HM','Christiana Healthcare','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'HN','Ontario Institute for Cancer Research (OICR)','Breast invasive carcinoma','NCH','BRCA';...
    'HP','Ontario Institute for Cancer Research (OICR)','Liver hepatocellular carcinoma','NCH','LIHC';...
    'HQ','Ontario Institute for Cancer Research (OICR)','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'HR','Ontario Institute for Cancer Research (OICR)','Skin Cutaneous Melanoma','NCH','SKCM';...
    'HS','Ontario Institute for Cancer Research (OICR)','Sarcoma','NCH','SARC';...
    'HT','Case Western - St Joes','Brain Lower Grade Glioma','IGC','LGG';...
    'HU','National Cancer Center Korea','Stomach adenocarcinoma','IGC','STAD';...
    'HV','National Cancer Center Korea','Pancreatic adenocarcinoma','IGC','PAAD';...
    'HW','MSKCC','Brain Lower Grade Glioma','IGC','LGG';...
    'HZ','International Genomics Consortium','Pancreatic adenocarcinoma','IGC','PAAD';...
    'IA','Cleveland Clinic','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'IB','Alberta Health Services','Pancreatic adenocarcinoma','IGC','PAAD';...
    'IC','University of Pittsburgh','Esophageal carcinoma ','NCH','ESCA';...
    'IE','ABS - IUPUI','Sarcoma','NCH','SARC';...
    'IF','University of Texas MD Anderson Cancer Center','Sarcoma','NCH','SARC';...
    'IG','Asterand','Esophageal carcinoma ','NCH','ESCA';...
    'IH','University of Miami','Skin Cutaneous Melanoma','NCH','SKCM';...
    'IJ','Christiana Healthcare','Acute Myeloid Leukemia','NCH','LAML';...
    'IK','Christiana Healthcare','Brain Lower Grade Glioma','IGC','LGG';...
    'IM','University of Miami','Thyroid carcinoma','NCH','THCA';...
    'IN','University of Pittsburgh','Stomach adenocarcinoma','IGC','STAD';...
    'IP','ABS - IUPUI','Stomach adenocarcinoma','IGC','STAD';...
    'IQ','University of Miami','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'IR','Memorial Sloan Kettering','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'IS','Memorial Sloan Kettering','Sarcoma','NCH','SARC';...
    'IW','Cedars Sinai','Sarcoma','NCH','SARC';...
    'IZ','ABS - Lahey Clinic','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'J1','ABS - Lahey Clinic','Lung squamous cell carcinoma','IGC','LUSC';...
    'J2','ABS - Lahey Clinic','Lung adenocarcinoma','IGC','LUAD';...
    'J4','ABS - Lahey Clinic','Prostate adenocarcinoma','IGC','PRAD';...
    'J7','ILSBio','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'J8','Mayo Clinic','Thyroid carcinoma','NCH','THCA';...
    'J9','Melbourne Health','Prostate adenocarcinoma','IGC','PRAD';...
    'JA','ABS - Research Metrics Pakistan','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'JL','ABS - Research Metrics Pakistan','Breast invasive carcinoma','NCH','BRCA';...
    'JU','BLN - Baylor','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'JV','BLN - Baylor','Sarcoma','NCH','SARC';...
    'JW','BLN - Baylor','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'JX','Washington University','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'JY','University Health Network','Esophageal carcinoma ','NCH','ESCA';...
    'JZ','University of Rochester','Esophageal carcinoma ','NCH','ESCA';...
    'K1','University of Pittsburgh','Sarcoma','NCH','SARC';...
    'K4','ABS - Lahey Clinic','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'K6','ABS - Lahey Clinic','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'K7','ABS - Lahey Clinic','Liver hepatocellular carcinoma','NCH','LIHC';...
    'K8','ABS - Lahey Clinic','Skin Cutaneous Melanoma','NCH','SKCM';...
    'KA','ABS - Lahey Clinic','Esophageal carcinoma ','NCH','ESCA';...
    'KB','University Health Network, Toronto','Stomach adenocarcinoma','IGC','STAD';...
    'KC','Cornell Medical College','Prostate adenocarcinoma','IGC','PRAD';...
    'KD','Mount Sinai School of Medicine','Sarcoma','NCH','SARC';...
    'KE','Mount Sinai School of Medicine','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'KF','Christiana Healthcare','Sarcoma','NCH','SARC';...
    'KG','Baylor Network','Pancreatic adenocarcinoma','IGC','PAAD';...
    'KH','Memorial Sloan Kettering','Esophageal carcinoma ','NCH','ESCA';...
    'KJ','University of Miami','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'KK','MD Anderson Cancer Center','Prostate adenocarcinoma','IGC','PRAD';...
    'KL','MSKCC','Kidney Chromophobe','IGC','KICH';...
    'KM','NCI Urologic Oncology Branch','Kidney Chromophobe','IGC','KICH';...
    'KN','Harvard','Kidney Chromophobe','IGC','KICH';...
    'KO','MD Anderson Cancer Center','Kidney Chromophobe','IGC','KICH';...
    'KP','British Columbia Cancer Agency','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'KQ','Cornell Medical College','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'KR','University Of Michigan','Liver hepatocellular carcinoma','NCH','LIHC';...
    'KS','University Of Michigan','Thyroid carcinoma','NCH','THCA';...
    'KT','Hartford','Brain Lower Grade Glioma','IGC','LGG';...
    'KU','Hartford','Head and Neck squamous cell carcinoma','IGC','HNSC';...
    'KV','Hartford','Kidney renal papillary cell carcinoma','IGC','KIRP';...
    'KZ','Hartford','Stomach adenocarcinoma','IGC','STAD';...
    'L1','Hartford','Pancreatic adenocarcinoma','IGC','PAAD';...
    'L3','Gundersen Lutheran Health System','Lung squamous cell carcinoma','IGC','LUSC';...
    'L4','Gundersen Lutheran Health System','Lung adenocarcinoma','IGC','LUAD';...
    'L5','University of Michigan','Esophageal carcinoma ','NCH','ESCA';...
    'L6','National Institutes of Health','Thyroid carcinoma','NCH','THCA';...
    'L7','Christiana Care','Esophageal carcinoma ','NCH','ESCA';...
    'L8','University of Miami','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'L9','Candler','Lung adenocarcinoma','IGC','LUAD';...
    'LA','Candler','Lung squamous cell carcinoma','IGC','LUSC';...
    'LB','Candler','Pancreatic adenocarcinoma','IGC','PAAD';...
    'LC','Hartford Hospital','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'LD','Hartford Hospital','Breast invasive carcinoma','NCH','BRCA';...
    'LG','Hartford Hospital','Liver hepatocellular carcinoma','NCH','LIHC';...
    'LH','Hartford Hospital','Skin Cutaneous Melanoma','NCH','SKCM';...
    'LI','Hartford Hospital','Sarcoma','NCH','SARC';...
    'LK','University of Pittsburgh','Mesothelioma','NCH','MESO';...
    'LL','Candler','Breast invasive carcinoma','NCH','BRCA';...
    'LN','ILSBIO','Esophageal carcinoma ','NCH','ESCA';...
    'LP','ILSBIO','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'LQ','Gundersen Lutheran Health System','Breast invasive carcinoma','NCH','BRCA';...
    'LS','Gundersen Lutheran Health System','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'LT','Gundersen Lutheran Health System','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'M7','University of North Carolina','Prostate adenocarcinoma','NCH','PRAD';...
    'M8','Ontario Institute for Cancer Research (OICR)','Pancreatic adenocarcinoma','NCH','PAAD';...
    'M9','Ontario Institute for Cancer Research (OICR)','Esophageal carcinoma ','NCH','ESCA';...
    'MA','MD Anderson Cancer Center','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'MB','University of Minnesota','Sarcoma','NCH','SARC';...
    'ME','University of Minnesota','Lung adenocarcinoma','NCH','LUAD';...
    'MF','University of Minnesota','Lung squamous cell carcinoma','NCH','LUSC';...
    'MG','BLN - Baylor','Prostate adenocarcinoma','NCH','PRAD';...
    'MH','BLN - Baylor','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'MI','BLN - Baylor','Liver hepatocellular carcinoma','NCH','LIHC';...
    'MJ','BLN - Baylor','Sarcoma','NCH','SARC';...
    'MK','BLN - Baylor','Thyroid carcinoma','NCH','THCA';...
    'ML','BLN - Baylor','Lung squamous cell carcinoma','NCH','LUSC';...
    'MM','BLN - Baylor','Kidney renal clear cell carcinoma','NCH','KIRC';...
    'MN','BLN - Baylor','Lung adenocarcinoma','NCH','LUAD';...
    'MO','ILSBio','Sarcoma','NCH','SARC';...
    'MP','Washington University - Mayo Clinic','Lung adenocarcinoma','NCH','LUAD';...
    'MQ','Washington University - NYU','Mesothelioma','NCH','MESO';...
    'MR','University of Minnesota','Liver hepatocellular carcinoma','NCH','LIHC';...
    'MS','University of Minnesota','Breast invasive carcinoma','NCH','BRCA';...
    'MT','University of Minnesota','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'MU','University of Minnesota','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'MV','University of Minnesota','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'MW','University of Miami','Kidney renal clear cell carcinoma','NCH','KIRC';...
    'MX','MSKCC','Stomach adenocarcinoma','NCH','STAD';...
    'MY','Montefiore Medical Center','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'MZ','Montefiore Medical Center','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'N1','Montefiore Medical Center','Sarcoma','NCH','SARC';...
    'N5','MSKCC','Uterine Carcinosarcoma','NCH','UCS';...
    'N6','University of Pittsburgh','Uterine Carcinosarcoma','NCH','UCS';...
    'N7','Washington University','Uterine Carcinosarcoma','NCH','UCS';...
    'N8','University of North Carolina','Uterine Carcinosarcoma','NCH','UCS';...
    'N9','MD Anderson','Uterine Carcinosarcoma','NCH','UCS';...
    'NA','Duke University','Uterine Carcinosarcoma','NCH','UCS';...
    'NB','Washington University - CHUV','Lung adenocarcinoma','NCH','LUAD';...
    'NC','Washington University - CHUV','Lung squamous cell carcinoma','NCH','LUSC';...
    'ND','Cedars Sinai','Uterine Carcinosarcoma','NCH','UCS';...
    'NF','Mayo Clinic - Rochester','Uterine Carcinosarcoma','NCH','UCS';...
    'NG','Roswell Park','Uterine Carcinosarcoma','NCH','UCS';...
    'NH','Candler','Colon adenocarcinoma','NCH','COAD';...
    'NI','Roswell Park','Liver hepatocellular carcinoma','NCH','LIHC';...
    'NJ','Washington University - Rush University','Lung adenocarcinoma','NCH','LUAD';...
    'NK','Washington University - Rush University','Lung squamous cell carcinoma','NCH','LUSC';...
    'NM','Cambridge BioSource','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'NP','International Genomics Consortium','Kidney Chromophobe','NCH','KICH';...
    'NQ','International Genomics Consortium','Mesothelioma','NCH','MESO';...
    'NS','Gundersen Lutheran Health System','Skin Cutaneous Melanoma','NCH','SKCM';...
    'O1','Washington University - CALGB','Lung adenocarcinoma','NCH','LUAD';...
    'O2','Washington University - CALGB','Lung squamous cell carcinoma','NCH','LUSC';...
    'O8','Saint Marys Health Care','Liver hepatocellular carcinoma','NCH','LIHC';...
    'O9','Saint Marys Health Care','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'OC','Saint Marys Health Care','Lung squamous cell carcinoma','NCH','LUSC';...
    'OD','Saint Marys Health Care','Skin Cutaneous Melanoma','NCH','SKCM';...
    'OE','Saint Marys Health Care','Pancreatic adenocarcinoma','NCH','PAAD';...
    'OJ','Saint Marys Health Care','Thyroid carcinoma','NCH','THCA';...
    'OK','Mount Sinai School of Medicine','Breast invasive carcinoma','NCH','BRCA';...
    'OL','University of Chicago','Breast invasive carcinoma','NCH','BRCA';...
    'OR','University of Michigan','Adrenocortical carcinoma','NCH','ACC';...
    'OU','Roswell Park','Adrenocortical carcinoma','NCH','ACC';...
    'OW','International Genomics Consortium','Miscellaneous','NCH','MISC';...
    'OX','University of North Carolina','Glioblastoma multiforme','NCH','GBM';...
    'OY','University of North Carolina','Ovarian serous cystadenocarcinoma','NCH','OV';...
    'P3',' Fred Hutchinson','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'P4',' MD Anderson Cancer Center','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'P5','Cureline','Brain Lower Grade Glioma','NCH','LGG';...
    'P6','Translational Genomics Research Institute','Adrenocortical carcinoma','NCH','ACC';...
    'P7','Translational Genomics Research Institute','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'P8','University of Pittsburgh','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'P9','University of Minnesota','Pancreatic adenocarcinoma','NCH','PAAD';...
    'PA','University of Minnesota','Adrenocortical carcinoma','NCH','ACC';...
    'PB','University of Minnesota','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','NCH','DLBC';...
    'PC','Fox Chase','Sarcoma','NCH','SARC';...
    'PD','Fox Chase','Liver hepatocellular carcinoma','NCH','LIHC';...
    'PE','Fox Chase','Breast invasive carcinoma','NCH','BRCA';...
    'PG','Montefiore Medical Center','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'PH','Gundersen Lutheran','Acute Myeloid Leukemia','NCH','LAML';...
    'PJ','Gundersen Lutheran','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'PK','University Health Network','Adrenocortical carcinoma','NCH','ACC';...
    'PL','Institute of Human Virology Nigeria','Breast invasive carcinoma','NCH','BRCA';...
    'PN','Institute of Human Virology Nigeria','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'PQ','University of Colorado Denver','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'PR','Roswell Park','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'PT','Maine Medical Center','Sarcoma','NCH','SARC';...
    'PZ',' ABS - Lahey Clinic','Pancreatic adenocarcinoma','NCH','PAAD';...
    'Q1','University of Oklahoma HSC','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'Q2','University of Oklahoma HSC','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'Q3','University of Oklahoma HSC','Pancreatic adenocarcinoma','NCH','PAAD';...
    'Q4','Emory University','Acute Myeloid Leukemia','NCH','LAML';...
    'Q9','Emory University','Esophageal carcinoma ','NCH','ESCA';...
    'QA','Emory University','Liver hepatocellular carcinoma','NCH','LIHC';...
    'QB','Emory University','Skin Cutaneous Melanoma','NCH','SKCM';...
    'QC','Emory University','Sarcoma','NCH','SARC';...
    'QD','Emory University','Thyroid carcinoma','NCH','THCA';...
    'QF','BLN - Baylor','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'QG','BLN - Baylor','Colon adenocarcinoma','NCH','COAD';...
    'QH','Fondazione-Besta','Brain Lower Grade Glioma','NCH','LGG';...
    'QJ','Mount Sinai School of Medicine','Ovarian serous cystadenocarcinoma','NCH','OV';...
    'QK','Emory University - Winship Cancer Inst.','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'QL',' University of Chicago','Colon adenocarcinoma','NCH','COAD';...
    'QM','University of Oklahoma HSC','Uterine Carcinosarcoma','NCH','UCS';...
    'QN','ILSBio','Uterine Carcinosarcoma','NCH','UCS';...
    'QQ','Roswell Park','Sarcoma','NCH','SARC';...
    'QR','National Institutes of Health','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'QS','Candler','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'QT','University of North Carolina','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'QU','Harvard Beth Israel','Prostate adenocarcinoma','NCH','PRAD';...
    'QV','Instituto Nacional de Cancerologia','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'QW','Instituto Nacional de Cancerologia','Stomach adenocarcinoma','NCH','STAD';...
    'R1','CHI-Penrose Colorado','Colon adenocarcinoma','NCH','COAD';...
    'R2','CHI-Penrose Colorado','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'R3','CHI-Penrose Colorado','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'R5','MD Anderson Cancer Center','Stomach adenocarcinoma','NCH','STAD';...
    'R6','MD Anderson Cancer Center','Esophageal carcinoma ','NCH','ESCA';...
    'R7','Gundersen Lutheran Health System','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'R8','MD Anderson','Brain Lower Grade Glioma','NCH','LGG';...
    'R9','Candler','Ovarian serous cystadenocarcinoma','NCH','OV';...
    'RA','Candler','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'RB','Emory University','Pancreatic adenocarcinoma','NCH','PAAD';...
    'RC','University of Utah','Liver hepatocellular carcinoma','NCH','LIHC';...
    'RD','Peter MacCallum Cancer Center','Stomach adenocarcinoma','NCH','STAD';...
    'RE','Peter MacCallum Cancer Center','Esophageal carcinoma ','NCH','ESCA';...
    'RG','Montefiore Medical Center','Liver hepatocellular carcinoma','NCH','LIHC';...
    'RH','BLN - Baylor','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'RL','St. Josephs Hospital AZ','Pancreatic adenocarcinoma','NCH','PAAD';...
    'RM','St. Josephs Hospital AZ','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'RN','St. Josephs Hospital AZ','Sarcoma','NCH','SARC';...
    'RP','St. Josephs Hospital AZ','Skin Cutaneous Melanoma','NCH','SKCM';...
    'RQ','St. Josephs Hospital AZ','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','NCH','DLBC';...
    'RR','St. Josephs Hospital AZ','Glioblastoma multiforme','NCH','GBM';...
    'RS','Memorial Sloan Kettering Cancer Center','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'RT','Cleveland Clinic Foundation','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'RU','Northwestern University','Colon adenocarcinoma','NCH','COAD';...
    'RV','Northwestern University','Pancreatic adenocarcinoma','NCH','PAAD';...
    'RW','Michigan University','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'RX','University of Minnesota','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'RY','University of California San Francisco','Brain Lower Grade Glioma','NCH','LGG';...
    'RZ','Wills Eye Institute','Uveal Melanoma','NCH','UVM';...
    'S2','Albert Einstein Medical Center','Lung adenocarcinoma','NCH','LUAD';...
    'S3','Albert Einstein Medical Center','Breast invasive carcinoma','NCH','BRCA';...
    'S4','University of Chicago','Pancreatic adenocarcinoma','NCH','PAAD';...
    'S5',' University of Oklahoma HSC','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'S6','Gundersen Lutheran Health System','Testicular Germ Cell Tumors','NCH','TGCT';...
    'S7','University Hospital Motol','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'S8','ABS - IUPUI','Esophageal carcinoma ','NCH','ESCA';...
    'S9','Dept of Neurosurgery at University of Heidelberg','Brain Lower Grade Glioma','NCH','LGG';...
    'SA',' ABS - IUPUI','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'SB','Baylor College of Medicine','Testicular Germ Cell Tumors','NCH','TGCT';...
    'SC','Memorial Sloan Kettering','Mesothelioma','NCH','MESO';...
    'SD','MD Anderson','Pancreatic adenocarcinoma','NCH','PAAD';...
    'SE','Boston Medical Center','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'SG','Cleveland Clinic Foundation','Sarcoma','NCH','SARC';...
    'SH','Papworth Hospital','Mesothelioma','NCH','MESO';...
    'SI','Washington University St. Louis','Sarcoma','NCH','SARC';...
    'SJ','Albert Einstein Medical Center','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'SK','St. Josephs Hospital AZ','Colon adenocarcinoma','NCH','COAD';...
    'SL','St. Josephs Hospital AZ','Uterine Corpus Endometrial Carcinoma','NCH','UCEC';...
    'SN','BLN - Baylor','Testicular Germ Cell Tumors','NCH','TGCT';...
    'SO','University of Minnesota','Testicular Germ Cell Tumors','NCH','TGCT';...
    'SP','University Health Network','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'SQ','International Genomics Consortium','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'SR','Tufts Medical Center','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'SS',' Medical College of Georgia','Colon adenocarcinoma','NCH','COAD';...
    'ST','Global Bioclinical-Moldova','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'SU','Global Bioclinical-Moldova','Prostate adenocarcinoma','NCH','PRAD';...
    'SW','Global Bioclinical-Moldova','Stomach adenocarcinoma','NCH','STAD';...
    'SX','Mayo Clinic Arizona','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'SY','Mayo Clinic Arizona','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'T1','St. Josephs Hospital Arizona','Liver hepatocellular carcinoma','NCH','LIHC';...
    'T2','St. University of Colorado Denver','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'T3','Molecular Response','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'T6','Molecular Response','Lung adenocarcinoma','NCH','LUAD';...
    'T7','Molecular Response','Kidney renal clear cell carcinoma','NCH','KIRC';...
    'T9','Molecular Response','Colon adenocarcinoma','NCH','COAD';...
    'TE','Global BioClinical - Georgia','Skin Cutaneous Melanoma','NCH','SKCM';...
    'TG','Global BioClinical - Georgia','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'TK','Global BioClinical - Georgia','Prostate adenocarcinoma','NCH','PRAD';...
    'TL','Global BioClinical - Georgia','Stomach adenocarcinoma','NCH','STAD';...
    'TM','The University of New South Wales','Brain Lower Grade Glioma','NCH','LGG';...
    'TN',' Ohio State University','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'TP','Maine Medical Center','Prostate adenocarcinoma','NCH','PRAD';...
    'TQ','University of Sao Paulo','Brain Lower Grade Glioma','NCH','LGG';...
    'TR','Global Bioclinical-Moldova','Skin Cutaneous Melanoma','NCH','SKCM';...
    'TS','University of Pennsylvania','Mesothelioma','NCH','MESO';...
    'TT','University of Pennsylvania','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'TV','Wake Forest University','Breast invasive carcinoma','NCH','BRCA';...
    'UB','UCSF','Liver hepatocellular carcinoma','NCH','LIHC';...
    'UC','University of Washington','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'UD',' University of Western Australia','Mesothelioma','NCH','MESO';...
    'UE',' Asterand','Sarcoma','NCH','SARC';...
    'UF','Barretos Cancer Hospital','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'UJ',' Boston Medical Center','Lung squamous cell carcinoma','NCH','LUSC';...
    'UL',' Boston Medical Center','Breast invasive carcinoma','NCH','BRCA';...
    'UN',' Boston Medical Center','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'UP',' Boston Medical Center','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'UR',' Boston Medical Center','Prostate adenocarcinoma','NCH','PRAD';...
    'US','Garvan Institute of Medical Research','Pancreatic adenocarcinoma','NCH','PAAD';...
    'UT','Asbestos Diseases Research Institute','Mesothelioma','NCH','MESO';...
    'UU','Mary Bird Perkins Cancer Center - Our Lady of the Lake','Breast invasive carcinoma','NCH','BRCA';...
    'UV','Capital Biosciences','Liver hepatocellular carcinoma','NCH','LIHC';...
    'UW','University of North Carolina','Kidney Chromophobe','NCH','KICH';...
    'UY','University of California San Francisco','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'UZ','University of California San Francisco','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'V1','University of California San Francisco','Prostate adenocarcinoma','NCH','PRAD';...
    'V2','Cleveland Clinic Foundation','Prostate adenocarcinoma','NCH','PRAD';...
    'V3','Cleveland Clinic Foundation','Uveal Melanoma','NCH','UVM';...
    'V4','Institut Curie','Uveal Melanoma','NCH','UVM';...
    'V5','Duke University','Esophageal carcinoma ','NCH','ESCA';...
    'V6','Duke University','Stomach adenocarcinoma','NCH','STAD';...
    'V7','Medical College of Georgia','Breast invasive carcinoma','NCH','BRCA';...
    'V8','Medical College of Georgia','Kidney renal clear cell carcinoma','NCH','KIRC';...
    'V9','Medical College of Georgia','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'VA','Alliance','Stomach adenocarcinoma','NCH','STAD';...
    'VB','Global BioClinical - Georgia','Lymphoid Neoplasm Diffuse Large B-cell Lymphoma','NCH','DLBC';...
    'VD','University of Liverpool','Uveal Melanoma','NCH','UVM';...
    'VF','University of Pennsylvania','Testicular Germ Cell Tumors','NCH','TGCT';...
    'VG','Institute of Human Virology Nigeria','Ovarian serous cystadenocarcinoma','NCH','OV';...
    'VK','Institute of Human Virology Nigeria','Colon adenocarcinoma','NCH','COAD';...
    'VL','Institute of Human Virology Nigeria','Rectum adenocarcinoma','NCH','READ';...
    'VM','Huntsman Cancer Institute','Brain Lower Grade Glioma','NCH','LGG';...
    'VN','NCI Urologic Oncology Branch','Prostate adenocarcinoma','NCH','PRAD';...
    'VP','Washington University','Prostate adenocarcinoma','NCH','PRAD';...
    'VQ','Barretos Cancer Hospital','Stomach adenocarcinoma','NCH','STAD';...
    'VR','Barretos Cancer Hospital','Esophageal carcinoma ','NCH','ESCA';...
    'VS','Barretos Cancer Hospital','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'VT','Vanderbilt','Sarcoma','NCH','SARC';...
    'VV',' John Wayne Cancer Center','Brain Lower Grade Glioma','NCH','LGG';...
    'VW','Northwestern University','Brain Lower Grade Glioma','NCH','LGG';...
    'VX','Northwestern University','Stomach adenocarcinoma','NCH','STAD';...
    'VZ','Albert Einstein Medical Center','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'W2','Medical College of Wisconsin','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'W3',' John Wayne Cancer Center','Skin Cutaneous Melanoma','NCH','SKCM';...
    'W4','University of North Carolina','Testicular Germ Cell Tumors','NCH','TGCT';...
    'W5','Mayo Clinic Rochester','Cholangiocarcinoma','NCH','CHOL';...
    'W6','UCSF','Cholangiocarcinoma','NCH','CHOL';...
    'W7','Garvan Institute of Medical Research','Cholangiocarcinoma','NCH','CHOL';...
    'W8','Greenville Health System','Breast invasive carcinoma','NCH','BRCA';...
    'W9','University of Kansas','Brain Lower Grade Glioma','NCH','LGG';...
    'WA','University of Schleswig-Holstein','Head and Neck squamous cell carcinoma','NCH','HNSC';...
    'WB','Erasmus MC','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'WC','MD Anderson','Uveal Melanoma','NCH','UVM';...
    'WD',' Emory University','Cholangiocarcinoma','NCH','CHOL';...
    'WE',' Norfolk and Norwich Hospital','Skin Cutaneous Melanoma','NCH','SKCM';...
    'WF','Greenville Health System','Pancreatic adenocarcinoma','NCH','PAAD';...
    'WG','Greenville Health System','Lung squamous cell carcinoma','NCH','LUSC';...
    'WH','Greenville Health System','Brain Lower Grade Glioma','NCH','LGG';...
    'WJ','Greenville Health System','Liver hepatocellular carcinoma','NCH','LIHC';...
    'WK','Brigham and Womens Hospital','Sarcoma','NCH','SARC';...
    'WL','University of Kansas','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'WM','University of Kansas','Kidney renal clear cell carcinoma','NCH','KIRC';...
    'WN','University of Kansas','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'WP','University of Kansas','Sarcoma','NCH','SARC';...
    'WQ','University of Kansas','Liver hepatocellular carcinoma','NCH','LIHC';...
    'WR','University of Kansas','Ovarian serous cystadenocarcinoma','NCH','OV';...
    'WS','University of Kansas','Colon adenocarcinoma','NCH','COAD';...
    'WT','University of Kansas','Breast invasive carcinoma','NCH','BRCA';...
    'WU','Wake Forest University','Colon adenocarcinoma','NCH','COAD';...
    'WW','Wake Forest University','Prostate adenocarcinoma','NCH','PRAD';...
    'WX','Yale University','Liver hepatocellular carcinoma','NCH','LIHC';...
    'WY','Johns Hopkins','Brain Lower Grade Glioma','NCH','LGG';...
    'WZ',' International Genomics Consortium','Testicular Germ Cell Tumors','NCH','TGCT';...
    'X2','University of Washington','Sarcoma','NCH','SARC';...
    'X3','Cleveland Clinic Foundation','Testicular Germ Cell Tumors','NCH','TGCT';...
    'X4','Institute for Medical Research','Prostate adenocarcinoma','NCH','PRAD';...
    'X5','Institute of Human Virology Nigeria','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'X6','University of Iowa','Sarcoma','NCH','SARC';...
    'X7','ABS IUPUI','Thymoma','NCH','THYM';...
    'X8','St. Josephs Hospital Arizona','Esophageal carcinoma ','NCH','ESCA';...
    'X9','University of California, Davis','Sarcoma','NCH','SARC';...
    'XA',' University of Minnesota','Prostate adenocarcinoma','NCH','PRAD';...
    'XB','Albert Einstein Medical Center','Esophageal carcinoma ','NCH','ESCA';...
    'XC','Albert Einstein Medical Center','Lung squamous cell carcinoma','NCH','LUSC';...
    'XD','Providence Portland Medical Center','Pancreatic adenocarcinoma','NCH','PAAD';...
    'XE','University of Southern California','Testicular Germ Cell Tumors','NCH','TGCT';...
    'XF','University of Southern California','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'XG','BLN UT Southwestern Medical Center at Dallas','Pheochromocytoma and Paraganglioma','NCH','PCPG';...
    'XH','BLN Baylor','Thymoma','NCH','THYM';...
    'XJ','University of Kansas','Prostate adenocarcinoma','NCH','PRAD';...
    'XK','Mayo Clinic Arizona','Prostate adenocarcinoma','NCH','PRAD';...
    'XM','MSKCC','Thymoma','NCH','THYM';...
    'XN','University of Sao Paulo','Pancreatic adenocarcinoma','NCH','PAAD';...
    'XP','University of Sao Paulo','Esophageal carcinoma ','NCH','ESCA';...
    'XQ','University of Sao Paulo','Prostate adenocarcinoma','NCH','PRAD';...
    'XR','University of Sao Paulo','Liver hepatocellular carcinoma','NCH','LIHC';...
    'XS','University of Sao Paulo','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'XT','Johns Hopkins','Mesothelioma','NCH','MESO';...
    'XU','University Health Network','Thymoma','NCH','THYM';...
    'XV',' Capital Biosciences','Skin Cutaneous Melanoma','NCH','SKCM';...
    'XX','Spectrum Health','Breast invasive carcinoma','NCH','BRCA';...
    'XY','Spectrum Health','Testicular Germ Cell Tumors','NCH','TGCT';...
    'Y3','University of New Mexico','Acute Myeloid Leukemia','NCH','LAML';...
    'Y5','University of Arizona','Sarcoma','NCH','SARC';...
    'Y6','University of Arizona','Prostate adenocarcinoma','NCH','PRAD';...
    'Y8','Spectrum Health','Kidney renal papillary cell carcinoma','NCH','KIRP';...
    'YA','Spectrum Health','Liver hepatocellular carcinoma','NCH','LIHC';...
    'YB','Spectrum Health','Pancreatic adenocarcinoma','NCH','PAAD';...
    'YC','Spectrum Health','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'YD','Spectrum Health','Skin Cutaneous Melanoma','NCH','SKCM';...
    'YF','University of Puerto Rico','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'YG','University of Puerto Rico','Skin Cutaneous Melanoma','NCH','SKCM';...
    'YH','Stanford University','Pancreatic adenocarcinoma','NCH','PAAD';...
    'YJ','Stanford University','Prostate adenocarcinoma','NCH','PRAD';...
    'YL','PROCURE Biobank','Prostate adenocarcinoma','NCH','PRAD';...
    'YN','University of Arizona','Skin Cutaneous Melanoma','NCH','SKCM';...
    'YR','Barretos Cancer Hospital','Cholangiocarcinoma','NCH','CHOL';...
    'YS','Barretos Cancer Hospital','Mesothelioma','NCH','MESO';...
    'YT','Barretos Cancer Hospital','Thymoma','NCH','THYM';...
    'YU','Barretos Cancer Hospital','Testicular Germ Cell Tumors','NCH','TGCT';...
    'YV','MSKCC','Uveal Melanoma','NCH','UVM';...
    'YW','Albert Einstein Medical Center','Sarcoma','NCH','SARC';...
    'YX','Emory University','Stomach adenocarcinoma','NCH','STAD';...
    'YY','Roswell Park','Pancreatic adenocarcinoma','NCH','PAAD';...
    'YZ','The Ohio State University','Uveal Melanoma','NCH','UVM';...
    'Z2','IDI-IRCCS','Skin Cutaneous Melanoma','NCH','SKCM';...
    'Z3','UCLA','Sarcoma','NCH','SARC';...
    'Z4','Cureline','Sarcoma','NCH','SARC';...
    'Z5','Cureline','Pancreatic adenocarcinoma','NCH','PAAD';...
    'Z6','Cureline','Esophageal carcinoma ','NCH','ESCA';...
    'Z7','John Wayne Cancer Center','Breast invasive carcinoma','NCH','BRCA';...
    'Z8','John Wayne Cancer Center','Pancreatic adenocarcinoma','NCH','PAAD';...
    'ZA','Candler','Stomach adenocarcinoma','NCH','STAD';...
    'ZB','Thoraxklinik','Thymoma','NCH','THYM';...
    'ZC',' University of Mannheim','Thymoma','NCH','THYM';...
    'ZD','ILSbio','Cholangiocarcinoma','NCH','CHOL';...
    'ZE','Spectrum Health','Lung squamous cell carcinoma','NCH','LUSC';...
    'ZF','University of Sheffield','Bladder Urothelial Carcinoma','NCH','BLCA';...
    'ZG','University Medical Center Hamburg-Eppendorf','Prostate adenocarcinoma','NCH','PRAD';...
    'ZH','University of North Carolina','Cholangiocarcinoma','NCH','CHOL';...
    'ZJ','NCI HRE Branch','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC';...
    'ZK','University of New Mexico','Cholangiocarcinoma','NCH','CHOL';...
    'ZL','Valley Hospital','Thymoma','NCH','THYM';...
    'ZM','University of Ulm','Testicular Germ Cell Tumors','NCH','TGCT';...
    'ZN','Brigham and Womens Hospital Division of Thoracic Surgery','Mesothelioma','NCH','MESO';...
    'ZP','Medical College of Wisconsin','Liver hepatocellular carcinoma','NCH','LIHC';...
    'ZQ','Tayside Tissue Bank','Stomach adenocarcinoma','NCH','STAD';...
    'ZR','Tayside Tissue Bank','Esophageal carcinoma ','NCH','ESCA';...
    'ZS','Tayside Tissue Bank','Liver hepatocellular carcinoma','NCH','LIHC';...
    'ZT',' International Genomics Consortium','Thymoma','NCH','THYM';...
    'ZU','Spectrum Health','Cholangiocarcinoma','NCH','CHOL';...
    'ZW','University of Alabama','Pancreatic adenocarcinoma','NCH','PAAD';...
    'ZX','University of Alabama','Cervical squamous cell carcinoma and endocervical adenocarcinoma','NCH','CESC'};
if ~iscell(IDs)
    IDs = {IDs};
end
numSamples = length(IDs);
maxNumChar = max(cellfun(@(x) length(x),IDs,'UniformOutput',true));
if maxNumChar >= 15   
    SampleFields = {'SampleId','TCGA_Code','Study_Name','Source_Site','Participant','Sample_Type','Sample_Type_Short'}';
    SampleInfo = cell(numSamples,7);
elseif maxNumChar >= 12
    SampleFields = {'SampleId','TCGA_Code','Study_Name','Source_Site','Participant'}';
    SampleInfo = cell(numSamples,5);   
elseif maxNumChar >= 7
    SampleFields = {'SampleId','TCGA_Code','Study_Name','Source_Site'}';
    SampleInfo = cell(numSamples,4);
else
    SampleFields = {'SampleId'}';
    SampleInfo = cell(numSamples,1);
end
SampleInfo(:) = {''};

for i=1:numSamples   
    SampleId = IDs{i};
    numChar = length(SampleId);
    SampleInfo{i,1} = SampleId;    
    if numChar >= 7
        TSS_num = SampleId(6:7);
        indx = strcmp(TSS_num,TSS_Indx(:,1));
        if any(indx)
            SampleInfo{i,2} = TSS_Indx{indx,5};
            SampleInfo{i,3} = TSS_Indx{indx,3};
            SampleInfo{i,4} = TSS_Indx{indx,2};
        end
      
    end
    if numChar >= 12
        SampleInfo{i,5} = SampleId(1:12);
    end
    if numChar >= 15        
        Sample_num = SampleId(14:15);    
        indx = strcmp(Sample_num,SampleTypeIndx(:,1));
        if any(indx)
            SampleInfo(i,6) = SampleTypeIndx(indx,2);
            SampleInfo(i,7) = SampleTypeIndx(indx,3);
        end
    end
end






